PROJECT_VERSION_VCS_LONG = "${PROJECT_VERSION_VCS_LONG}"
PROJECT_VERSION_GIT_ID = "${PROJECT_VERSION_GIT_ID}"
PROJECT_VERSION_MBS = "${PROJECT_VERSION}"
BUILD_TYPE = "${BUILD_TYPE}"
BUILD_TIME = "${BUILD_TIME}"
FLASHER_VERSION_STRING="CLI Flasher v${PROJECT_VERSION}${BUILD_TYPE} ${BUILD_TIME}\n    ${PROJECT_VERSION_VCS_LONG}"

