name: CI Build

# Specify when to run the CI Build
on:
  # Run when a tag is pushed (set)
  push:
    tags:
      - '*' # Accept any tag name

  # Run when a pull request is opened, reopened or a new change is added to it
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        # Ubuntu 18 seems to lack GLIBC_2.28 which is required for upload-artifact@v4.
        #- name: Ubuntu 18.04 x86
        #  image: ghcr.io/muhkuh-sys/mbs_ubuntu_1804_x86:latest
        #  distribution-id: ubuntu
        #  distribution-version: "18.04"
        #  cpu-architecture: x86
        #- name: Ubuntu 18.04 x86_64
        #  image: ghcr.io/muhkuh-sys/mbs_ubuntu_1804_x86_64:latest
        #  distribution-id: ubuntu
        #  distribution-version: "18.04"
        #  cpu-architecture: x86_64
        #- name: Ubuntu 18.04 arm64
        #  image: ghcr.io/muhkuh-sys/mbs_ubuntu_1804_x86_64:latest
        #  distribution-id: ubuntu
        #  distribution-version: "18.04"
        #  cpu-architecture: arm64

        # 32bit linux runners seem to be no longer supported.
        #- name: Ubuntu 20.04 x86
        #  image: ghcr.io/muhkuh-sys/mbs_ubuntu_2004_x86:latest
        #  distribution-id: ubuntu
        #  distribution-version: "20.04"
        #  cpu-architecture: x86
        - name: Ubuntu 20.04 x86_64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2004_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "20.04"
          cpu-architecture: x86_64
        - name: Ubuntu 20.04 arm64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2004_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "20.04"
          cpu-architecture: arm64
        - name: Ubuntu 22.04 x86_64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: x86_64
        - name: Ubuntu 22.04 armhf
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: armhf
        - name: Ubuntu 22.04 arm64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: arm64
        - name: Ubuntu 22.04 riscv64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: riscv64
        - name: Windows x86
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: windows
          distribution-version: ""
          cpu-architecture: x86
        - name: Windows x86_64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: windows
          distribution-version: ""
          cpu-architecture: x86_64
    container: ${{ matrix.platform.image }}

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Checkout all submodules recursively
        submodules: recursive

        # Fetch the full history for working "git describe"
        fetch-depth: 0

        # Fetch git tags
        fetch-tags: true

    # Disable git safe directory
    - name: Disable Git safe directory
      run: git config --system --add safe.directory '*'

    # Install pip and use it to install gitpython
    - name: Install pip and get dependencies for build script
      run:  apt update && apt install -y python3-pip && python3 -m pip install gitpython

    # TEST: Get info about the current repository state
    - name: git status
      run: git status
    - name: git graph
      run: git log --all --decorate --oneline --graph
    - name: git describe
      run: git describe
    - name: git describe always
      run: git describe --always
    
    # Run the actual build process
    - name: Build flasher
      run: python3 build_artifact.py ${{ matrix.platform.distribution-id }} ${{ matrix.platform.distribution-version }} ${{ matrix.platform.cpu-architecture }}
    
          # Upload the artifact
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        # Name of the artifact to upload.
        name: artifacts_${{ matrix.platform.distribution-id }}${{ matrix.platform.distribution-version }}_${{ matrix.platform.cpu-architecture }}

        # What to upload
        path: flasher-environment/build/artifacts/*

        # Expiration time period in days
        retention-days: 30